language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "tqlin"
  - git config user.email "smltq@126.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push origin master

branches:
  only:
    - master